Repository pluralsh/documentation, pull requests merged in 2022-06, with the labels that each got.

#8 Update CLI Quickstart with OAuth instructions
  getting-started/README.md
  repositories/README.md
Labels: fixes

#1 WIP: docs on how to customize Plural applications
  README.md
  SUMMARY.md
  adding-new-application/README.md
  adding-new-application/guide.md
  api/introduction/README.md
  api/introduction/console-api.md
  architecture-1.md
  getting-started/README.md
  workspace/secret-management.md
  workspace/workspace-layout.md
Labels: tutorial, reference, fixes

#11 Update README.md
  getting-started/README.md
Labels: fixes

#13 Add note about delayed SSL convergence
  getting-started/README.md
  getting-started/cloud-shell-quickstart.md
Labels: fixes

#10 Rename github to GitHub
  basics/GettingStarted.md
  getting-started/README.md
  getting-started/cloud-shell.md
  identity-and-access-management/identity-and-installations/sharing-existing-plural-installation-repos.md
Labels: fixes

#14 Docs Restructuring and Quickstart Overhaul
  README.md
  SUMMARY.md
  getting-started/README.md
  getting-started/admin-console.md
  getting-started/uninstall.md
  reference/README.md
  reference/api/introduction/README.md
  reference/api/introduction/console-api.md
  reference/api/introduction/plural-api.md
  reference/debugging/README.md
  reference/debugging/health-checks.md
  reference/debugging/logs.md
  reference/debugging/proxies.md
  reference/identity-and-access-management/README.md
  reference/identity-and-access-management/api-tokens.md
  reference/identity-and-access-management/identity-and-installations/README.md
  reference/identity-and-access-management/identity-and-installations/audit-logging.md
  reference/identity-and-access-management/identity-and-installations/service-accounts.md
  reference/identity-and-access-management/identity-and-installations/sharing-existing-plural-installation-repos.md
  reference/identity-and-access-management/introduction.md
  reference/identity-and-access-management/openid-connect.md
  reference/workspace/README.md
  reference/workspace/secret-management.md
  reference/workspace/workspace-layout.md
Labels: reorg, fixes

#16 Fix directory pathing
  README.md
  SUMMARY.md
  basic-setup-and-deployment/openid-connect.md
  basic-setup-and-deployment/quickstart.md
Labels: fixes

#17 Clarify the deployment options in Get Started
  README.md
Labels: reorg

#18 Docs cleanup after sprint changes
  README.md
  SUMMARY.md
  advanced-topics/identity-and-access-management/api-tokens.md
  advanced-topics/identity-and-access-management/identity-and-installations/README.md
  advanced-topics/identity-and-access-management/identity-and-installations/audit-logging.md
  advanced-topics/identity-and-access-management/identity-and-installations/service-accounts.md
  advanced-topics/identity-and-access-management/identity-and-installations/sharing-existing-repos.md
  getting-started/getting-started.md
  reference/api/README.md
  reference/api/console-api.md
  reference/api/plural-api.md
  reference/workspaces/README.md
  reference/workspaces/secret-management.md
  reference/workspaces/workspace-structure.md
Labels: fixes

#19 Change out discord links to custom URLs
  README.md
  basic-setup-and-deployment/cloud-shell-quickstart.md
  getting-started/getting-started.md
  reference/troubleshooting.md
Labels: reorg

#20 Add identity and Installations to summary.md
  SUMMARY.md
Labels: fixes

#21 Add Cloud Provider CLI doc
  basic-setup-and-deployment/configuring-cloud-provider.md
  getting-started/getting-started.md
Labels: tutorial
