Repository pluralsh/documentation, pull requests merged in 2024-09, with the labels that each got.

#304 Document PR Automation Testing
  pages/deployments/pr/testing.md
  src/NavData.tsx
Labels: features, new-content, enhancement, hotfix

#289 Prod 2450/how to use plural docs
  .vscode/settings.json
  pages/how-to/index.md
  pages/how-to/set-up/controllers.md
  pages/how-to/set-up/index.md
  pages/how-to/set-up/mgmt-cluster.md
  pages/how-to/set-up/pipelines.md
  pages/how-to/set-up/pr-automation.md
  pages/how-to/set-up/scm-connection.md
  pages/how-to/set-up/workload-cluster.md
  public/images/how-to/cluster-creator-btn.png
  public/images/how-to/cluster-creator-modal-0.png
  public/images/how-to/cluster-creator-modal-1.png
  public/images/how-to/cluster-creator-modal-2.png
  public/images/how-to/cluster-creator-obj.png
  public/images/how-to/console_create-scm-btn.png
  public/images/how-to/console_create-scm-modal.png
  public/images/how-to/create-scm-webhook-btn.png
  public/images/how-to/create-scm-webhook-modal-0.png
  public/images/how-to/create-scm-webhook-modal-1.png
  public/images/how-to/create-stack-modal-0.png
  public/images/how-to/create-stack-modal-1.png
  public/images/how-to/create-stack-modal-2.png
  public/images/how-to/k8s-dash-403.png
  public/images/how-to/new-global-service-1.png
  public/images/how-to/new-global-services-btn.png
  public/images/how-to/pending-approval-btn.png
  src/NavData.tsx
  src/generated/graphql.ts
  src/generated/pages.json
Labels: enhancement

#305 Rearrange some docs, rewrite some other docs
  .github/PULL_REQUEST_TEMPLATE.md
  pages/deployments/dashboard.md
  pages/deployments/notifications.md
  pages/deployments/operator/architecture.md
  pages/deployments/operator/helm-service.md
  pages/deployments/terraform-interop.md
  src/NavData.tsx
Labels: enhancement, hotfix

#311 update DS in doc site
  package.json
  src/components/DocSearchStyles.tsx
  src/components/SideNav.tsx
  src/components/TableOfContents.tsx
  src/generated/graphql.ts
  src/markdoc/nodes/index.ts
  yarn.lock
Labels: dependencies
