Repository pluralsh/documentation, pull requests merged in 2025-04, with the labels that each got.

#435 fix: Docs sync
  .github/workflows/ci.yaml
  .github/workflows/cron.yaml
  Makefile
  pages/overview/agent-api-reference.md
  pages/overview/management-api-reference.md
Labels: bug-fix

#437 bugfix: Observability typos
  .gitignore
  .vscode/settings.json
  pages/plural-features/observability/index.md
Labels: bug-fix

#439 Feat/restore files
  .gitignore
  .vscode/settings.json
Labels: documentation, bug-fix

#443 Base Flow documentation
  generated/routes.json
  pages/plural-features/flows/create-a-flow.md
  pages/plural-features/flows/flow-ai.md
  pages/plural-features/flows/index.md
  pages/plural-features/flows/mcp.md
  public/assets/flows/flow-ui.png
  public/assets/flows/mcp-connection.png
  public/assets/flows/mcp-server.png
  src/routing/docs-structure.ts
Labels: enhancement

#444 Add demo video for flows
  pages/plural-features/flows/index.md
Labels: enhancement

#449 update readme with new docs structure instructions
  README.md
Labels: enhancement, documentation
