Repository pluralsh/documentation, pull requests merged in 2025-01, with the labels that each got.

#369 Fix Youtube links
  pages/ai/overview.md
  pages/catalog/overview.md
Labels: hotfix

#376 fix controller set up page
  pages/how-to/set-up/controllers.md
  src/generated/pages.json
Labels: bug-fixes

#380 Remove marketplace link
  src/components/PageHeader.tsx
Labels: bug-fixes

#381 Move api reference to top level for fleet management
  src/NavData.tsx
Labels: documentation

#383 Explicitly disable proxy protocol for nginx for now
  pages/how-to/set-up/controllers.md
Labels: documentation
