Repository pluralsh/documentation, pull requests merged in 2025-06, with the labels that each got.

#463 Change configRef name
  pages/plural-features/pr-automation/crds.md
Labels: bug-fix

#468 add lua script doc
  generated/routes.json
  pages/plural-features/continuous-deployment/helm-service.md
  pages/plural-features/continuous-deployment/lua.md
  src/generated/graphql.ts
  src/routing/docs-structure.ts
Labels: new-content, enhancement

#471 extend lua doc
  generated/routes.json
  pages/plural-features/continuous-deployment/lua.md
Labels: enhancement, documentation
