Repository pluralsh/documentation, pull requests merged in 2025-03, with the labels that each got.

#426 Document Stack Export/Import
  pages/03-plural-features/03-stacks-iac-management/04-sharing-outputs.md
  pages/03-plural-features/03-stacks-iac-management/07-local-execution.md
  pages/03-plural-features/03-stacks-iac-management/08-service-contexts.md
  src/generated/pages.json
  src/routes/docs.generated.ts
  src/routing/navigation.ts
Labels: enhancement

#428 Document Plural Cloud setup flow
  pages/02-getting-started/01-first-steps/03-plural-cloud.md
  pages/02-getting-started/02-how-to-use/06-observability.md
  pages/02-getting-started/02-how-to-use/08-pr-automation.md
  pages/02-getting-started/02-how-to-use/09-pipelines.md
  public/assets/getting-started/cloud-start.png
  public/assets/getting-started/cloud-wizard.png
  public/assets/getting-started/devops-catalog.png
  public/assets/getting-started/log-filters.png
  public/assets/getting-started/log-tail.png
  public/assets/getting-started/metrics.png
  src/generated/pages.json
  src/routes/docs.generated.ts
  src/routing/navigation.ts
Labels: new-content

#431 docs: Document compatibility scraping
  Makefile
  generated/routes.json
  pages/plural-features/k8s-upgrade-assistant/addon-compatibilities.md
  public/assets/deployments/addon-compatibilities-details.png
  public/assets/deployments/addon-compatibilities.png
  src/routing/docs-structure.ts
Labels: new-content, enhancement, documentation

#434 update meta image and description
  public/og_image.png
  src/consts.ts
Labels: enhancement
