Repository pluralsh/documentation, pull requests merged in 2025-05, with the labels that each got.

#453 docs: new product update
  pages/resources/product-updates.md
Labels: fixes

#452 Observability Webhook Documentation
  generated/routes.json
  pages/plural-features/observability/index.md
  pages/plural-features/observability/observability-webhooks/datadog.md
  pages/plural-features/observability/observability-webhooks/grafana.md
  public/assets/observability/datadog-webhook-config.png
  public/assets/observability/datadog-webhook-url.png
  public/assets/observability/grafana-webhook-config.png
  public/assets/observability/grafana-webhook-url.png
  public/assets/observability/observability-webhooks-tab.png
  src/routing/docs-structure.ts
Labels: enhancement

#450 feat(docs): document observers under continuous deployment
  generated/routes.json
  pages/plural-features/continuous-deployment/observer.md
  src/routing/docs-structure.ts
Labels: enhancement, documentation

#455 Preview Environments Documentation
  generated/routes.json
  pages/plural-features/flows/index.md
  pages/plural-features/flows/preview-environments.md
  pages/plural-features/k8s-upgrade-assistant/index.md
  src/generated/graphql.ts
  src/routing/docs-structure.ts
Labels: new-content, enhancement

#448 feat(docs): document pipelines under continuous deployment
  .github/workflows/codeql.yml
  generated/routes.json
  pages/plural-features/continuous-deployment/pipelines.md
  src/routing/docs-structure.ts
Labels: enhancement, documentation

#456 Document ClusterDrain controller
  generated/routes.json
  pages/plural-features/k8s-upgrade-assistant/cluster-drain.md
  src/routing/docs-structure.ts
Labels: enhancement

#457 dockerize docs site
  .dockerignore
  .github/workflows/publish.yml
  .yarnrc.docker.yml
  Dockerfile
Labels: enhancement

#458 Make image vendoring more clear
  .github/PULL_REQUEST_TEMPLATE.md
  pages/getting-started/advanced-config/sandboxing.md
  pages/plural-features/flows/preview-environments.md
Labels: enhancement

#459 Add more clarification on the multi-tenancy docs
  pages/plural-features/projects-and-multi-tenancy/index.md
Labels: enhancement
